#!/data/data/com.termux/files/usr/bin/bash
tmp=~/.temp_wallpaper.png

rsync -av mightymime@jff.sh:~/wallpapers ~/.local/share

magick $(find ~/.local/share/wallpapers | shuf -n 1) -gravity center -extent 6:13 "$tmp"
termux-wallpaper -f "$tmp" -l
rm "$tmp"
