#!/data/data/com.termux/files/usr/bin/bash

_notification(){
	termux-notification \
		--title "UDM" \
		--content "$1" \
		--image-path ~/shortcuts/assets/udm_logo.jpg
	exit 1
}

rsync -av kiwi:~/music/ ~/Music ||
	_notification "failed syncing"
termux-media-scan ~/Music
_notification "finished syncing"
