#!/data/data/com.termux/files/usr/bin/bash
tmp=~/.temp_wallpaper.png

remote="mightymime@jff.sh"
if ping -c 1 kiwi &>/dev/null; then
    remote="mightymime@kiwi"
fi

rsync --delete -av --progress "$remote":~/.local/share/wallpapers ~/.local/share

magick $(find ~/.local/share/wallpapers -type f | shuf -n 1) -gravity center -extent 6:13 "$tmp"
termux-wallpaper -f "$tmp"
rm "$tmp"
