#!/data/data/com.termux/files/usr/bin/bash

case "$2" in
    --next|--previous|--back|--forward|--stop|--play-pause)
        ssh "$1" '~/.local/bin/udm '"$2"
        ;;
    \+|-|mute)
        ssh "$1" '~/.local/bin/deaf '"$2"
        ;;
esac
